open Ctypes

(* This Types_generated module is an instantiation of the Types functor defined
   in the type_description.ml file. It's generated by a C program that Dune
   creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open F

  let bfd_init = foreign "bfd_init" (void @-> returning int)

  let bfd_openw =
    foreign "bfd_openw" (string @-> string @-> returning (ptr Types.bfd))

  let bfd_close = foreign "bfd_close" (ptr Types.bfd @-> returning bool)
end
