name: CI Check
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - name: Install dependencies
        run: opam install . --deps-only --working-dir
      - name: Build
        run: opam exec -- dune build

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - feature: default

    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: Install dependencies
        run: opam install . --deps-only --working-dir
      - name: Run tests
        run: opam exec -- dune runtest

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      - name: Install dependencies
        run: opam install . --deps-only --working-dir
      - name: Format
        run: opam exec -- dune fmt --preview 
